language: php
php:
  - 5.3
  - 5.4
#  - 5.5
#  - 5.6
#  - 7.0
#  - hhvm
#  - nightly
matrix:
  allow_failures:
    - php: 7.0

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source
  - composer require squizlabs/php_codesniffe:2.0.*@dev

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover build/logs/clover.xml
  - ./vendor/bin/test-reporter
  - ./vendor/bin/phpcs --standard=PSR2 src/* tests/*