sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  # Update composer binary
  - composer self-update

before_script:
  # Install require & require-dev
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text --coverage-clover build/logs/clover.xml --coverage-html build/coverage
  - ./vendor/bin/phpcs

after_script:
  # TestReporter seem desn't work with these version og PHP
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then ./vendor/bin/test-reporter; fi
  # Full Website generator
  - if  [ $TRAVIS_PHP_VERSION = '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh generate-website.sh; fi
