language: php
php:
  - 5.3
#  - 5.4
#  - 5.5
#  - 5.6
#  - 7.0
#  - hhvm
#  - nightly
matrix:
  allow_failures:
    - php: 7.0

sudo: false

before_install:
  - composer self-update
  - composer install --prefer-source --dev

install: composer update --prefer-dist --no-interaction

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text